name: Deploy to Azure Web App
on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure you have a requirements.txt file
    - name: Collect static files
      run: python manage.py collectstatic --noinput

    - name: Run migrations
      run: python manage.py migrate 

    - name: 'Deploy to Azure Web App'
      uses: Azure/webapps-deploy@v2
      with:
        app-name: 'EZI'  # Your Azure App Service name
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
