name: Build and deploy Python app to Azure Web App - EZI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.9'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Collect static files
        run: python manage.py collectstatic --noinput
        
      - name: Run migrations
        run: python manage.py runserver
        
      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "venv/*" "*.git*" "node_modules/*"

      - name: List contents of ZIP
        run: unzip -l release.zip

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v3
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'EZI'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DA4FCF3D7B9A47C6B8CAD50F2EAB19A9 }}
